# Use an official OpenJDK runtime as a parent image
FROM ghcr.io/lab900/lisbon-hackathon-be:latest
EXPOSE 8080
# Run jar file when the container launches
CMD ["java", "-jar", "target/intrct-0.0.1-SNAPSHOT.jar"]